- id: nitpick
  name: Nitpick
  description: Enforce the same configuration (flake8, isort, mypy, pylint) across multiple Python projects
  entry: flake8 --select=NIP
  language: python
  types: [python]
  always_run: true
