# https://docs.travis-ci.com/user/reference/xenial/
dist: xenial

cache:
  directories:
    - $HOME/.cache/pip

# https://docs.travis-ci.com/user/languages/python/
language: python
python:
  - "3.6"
  - "3.7"
script:
  # Run some of the pre-commit hooks on Travis.
  # Running "pre-commit run --all-files" checks more files than expected;
  # e.g. it doesn't respect flake8's exclude config on setup.cfg.
  - black .
  - flake8
  - coverage run --source=flake8_nitpick -m pytest
  - safety check

install:
  - pip install -U poetry coveralls
  - pip install safety
  - poetry install

after_success:
  - coverage combine
  - "COVERALLS_PARALLEL=true coveralls"

notifications:
  webhooks: https://coveralls.io/webhook
