["pyproject.toml".tool.black]
line-length = 120

["pyproject.toml".tool.poetry.dev-dependencies]
black = {version = "*", allows-prereleases = true}
"flake8-blind-except" = "*"
"flake8-bugbear" = "*"
"flake8-comprehensions" = "*"
"flake8-debugger" = "*"
"flake8-docstrings" = "*"
"flake8-isort" = "*"
"flake8-mypy" = "*"
"flake8-polyfill" = "*"
"flake8-pytest" = "*"
"flake8" = "*"
pre_commit = "*"
ipython = "*"
ipdb = "*"
pylint = "*"
mypy = "*"

["setup.cfg".flake8]
ignore = "D107,D202,D203,D401,E203,E402,E501,W503"
max-line-length = 120

["setup.cfg".isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
