# Default style file for flake8-nitpick
# https://raw.githubusercontent.com/andreoliwa/flake8-nitpick/master/nitpick-style.toml

[nitpick]
minimum_version = "0.10.0"

[nitpick.styles]
include = [
    "styles/python36-37",
    "styles/poetry",
    "styles/absent-files",
    "styles/black",
    "styles/flake8",
    "styles/pylint",
    "styles/isort",
    "styles/mypy",
    "styles/pre-commit",
    "styles/pytest",
    "styles/ipython",
]

[nitpick.files."setup.cfg"]
comma_separated_values = ["flake8.ignore", "flake8.exclude", "isort.skip", "isort.known_first_party"]
