# Default style file for nitpick
# https://raw.githubusercontent.com/andreoliwa/nitpick/v0.20.0/nitpick-style.toml

[nitpick]
minimum_version = "0.10.0"

[nitpick.styles]
include = [
    "docs/styles/python37",
    "docs/styles/poetry",
    "docs/styles/absent-files",
    "docs/styles/pre-commit/main",
    "docs/styles/pre-commit/general",
    "docs/styles/pre-commit/python",
    "docs/styles/pre-commit/bash",
    "docs/styles/pre-commit/commitlint",
    "docs/styles/black",
    "docs/styles/flake8",
    "docs/styles/pylint",
    "docs/styles/isort",
    "docs/styles/mypy",
    "docs/styles/pytest",
    "docs/styles/ipython",
    "docs/styles/package-json",
]

[nitpick.files."setup.cfg"]
comma_separated_values = ["flake8.ignore", "flake8.exclude", "isort.skip", "isort.known_first_party"]
