[files]
"setup.cfg" = true
"Pipfile" = false
"Pipfile.lock" = false
"pyproject.toml" = true

["setup.cfg".flake8]
ignore = "D107,D202,D203,D401,E203,E402,E501,W503"
max-line-length = 120

["setup.cfg".isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
