[tool.black]
line-length = 120

[tool.poetry]
name = "flake8-nitpick"
version = "0.1.0"
description = "Flake8 plugin to share the same code style for multiple Python projects"
authors = ["Augusto Wagner Andreoli <andreoliwa@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]
"flake8" = "*"
"flake8-blind-except" = "*"
"flake8-bugbear" = "*"
"flake8-comprehensions" = "*"
"flake8-debugger" = "*"
"flake8-docstrings" = "*"
"flake8-isort" = "*"
"flake8-mypy" = "*"
"flake8-polyfill" = "*"
"flake8-pytest" = "*"
ipython = "*"
ipdb = "*"
pytest = "*"
twine = "*"
keyring = "*"
wheel = "*"
pre_commit = "*"
black = {version = "*", allows-prereleases = true}
pylint = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.nitpick."pyproject.toml".tool.black]
line-length = 120

[tool.nitpick."pyproject.toml".tool.poetry.dev-dependencies]
black = {version = "*", allows-prereleases = true}
"flake8-blind-except" = "*"
"flake8-bugbear" = "*"
"flake8-comprehensions" = "*"
"flake8-debugger" = "*"
"flake8-docstrings" = "*"
"flake8-isort" = "*"
"flake8-mypy" = "*"
"flake8-polyfill" = "*"
"flake8-pytest" = "*"
"flake8" = "*"
pre_commit = "*"
ipython = "*"
ipdb = "*"
pylint = "*"

[tool.nitpick."setup.cfg".flake8]
ignore = "D107,D202,D203,D401,E203,E402,E501,W503"
max-line-length = 120

[tool.nitpick."setup.cfg".isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
combine_as_imports = true
