# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

[nitpick.files."pre-commit-config.yaml"]
missing_message = "Create the file with the contents below, then run 'pre-commit install'"
